
-- 工作记录表
create table TB_WORK_LOG
(
id int generated by default as identity,
create_dt timestamp,
created_by int,
last_upd_dt timestamp,
last_upded_by int,
start_dt timestamp, -- 开始时间
end_dt timestamp, -- 结束时间
deadline timestamp, -- 最后截止时间
log_stat int, -- 状态
del_flag int default '0', -- 0:启用,1:删除
password varchar(20)
);

-- 字典表
create table TB_DICTIONARY
(
id int generated by default as identity,
dic_type varchar(50), -- 标明是用于什么内容的
dic_code varchar(200), -- 数据库中记录的值
dic_content varchar(300), -- 页面需要显示的值
dic_order_by int default '-1', -- 排序
active_flag char(1) default 'Y', -- 是否启用
del_flag int default '0', -- 0:未删除,1:删除
dic_comments varchar(300) -- 对此记录的注释
root_id int default '-1', -- 根记录此值等于id
parent_id int default '-1' -- 根记录此值等于 -1
);

-- 人员表
create table TB_USER
(
id int generated by default as identity,
username varchar(20), -- 登录名
password varchar(20), -- 密码
dispname varchar(50), -- 页面显示名
del_flag int default '0', -- 0:启用,1:删除
comments varchar(2000) -- 注释
);
